name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]  # develop 브랜치에 push가 일어날 때 실행

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4  # 저장소 코드 체크아웃

      - name: Set up JDK 17  # Java 개발 킷 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make application.yml  # application.yml 파일 생성
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: Grant execute permission for gradlew  # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle  # Gradle을 사용하여 프로젝트 빌드
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build -x test

      - name: Upload build artifact  # 빌드된 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: umc7thServer
          path: build/libs/*.jar
          retention-days: 1

  deploy:
    needs: build  # build 작업이 성공적으로 완료된 후 실행
    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifact  # 이전 단계에서 업로드한 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: umc7thServer
          path: build/libs/

      - name: Deploy to EC2  # EC2에 배포
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > bex1580.pem
          chmod 600 bex1580.pem
          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
          
          if [ -z "$jar_file" ]; then
            echo "No JAR file found"
            exit 1
          fi

          scp -i bex1580.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/umc7thServer.jar || exit 1
          ssh -i bex1580.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "            set -e
          if pgrep java; then
            pgrep java | xargs kill -15
            sleep 10
          fi
          nohup java -jar /home/$EC2_USERNAME/umc7thServer.jar > app.log 2>&1 &
            sleep 5
            if ! pgrep -f umc7thServer.jar; then
              echo 'Application failed to start' >&2
              exit 1
            fi
          " || exit 1

          rm -f bex1580.pem  # 민감한 정보 삭제